# version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - cache-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - cache-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cache-network

volumes:
  postgres-data:

networks:
  cache-network:
    driver: bridge

# What changed and why:

# env_file: .env — Docker reads variables from .env automatically
# ${POSTGRES_USER} — references the variable instead of hardcoding it
# lru_cache() on get_settings() — settings are only loaded once and cached in memory, not re-read on every request
# .env is in .gitignore — passwords never accidentally get committed


# What's happening here - O:

# 3 services — app, redis, postgres all talk to each other like separate machines but are on the same cache-network
# depends_on — ensures Redis and Postgres start before the app
# volumes: .:/app — maps your local code into the container, so --reload actually works
# postgres-data volume — Postgres data persists even if the container restarts. Without this, your database wipes every restart!
# alpine images — super lightweight Linux, keeps container sizes small
# cache-network: bridge — isolated private network, services talk to each other by service name (e.g. redis, postgres) not IP addresses